In [5]:
import numpy as np

In [10]:
list= [[1,2,3],[4,5,6],[7,8,9]]
list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr = np.array(list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [16]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones((3,4))  #tuples

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
arr1= np.linspace(0,3,10)
arr1.reshape(2,5)

array([[0.        , 0.33333333, 0.66666667, 1.        , 1.33333333],
       [1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(3,3)

array([[0.79963464, 0.06529666, 0.16758906],
       [0.67919425, 0.86992374, 0.47750176],
       [0.04090746, 0.06517914, 0.92874427]])

In [27]:
np.random.randn(4)

array([ 0.14818214,  0.29583999, -0.03979385, -0.75702367])

In [29]:
np.random.randint(2,20,10)

array([ 5,  3,  6,  9, 19,  6, 17, 12,  4,  4])

In [33]:
arr =np.arange(25)

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
np.random.rand(2,10)

array([[0.43571868, 0.18998139, 0.10882555, 0.57518444, 0.69331487,
        0.84284201, 0.12773671, 0.0499959 , 0.95404918, 0.76903568],
       [0.28062972, 0.38279431, 0.35939191, 0.99025232, 0.97329131,
        0.73280596, 0.24419863, 0.20970332, 0.91558356, 0.54528066]])

In [51]:
arr =np.random.randint(1,10,25)
arr

array([8, 8, 4, 1, 9, 1, 4, 6, 6, 5, 3, 6, 6, 3, 9, 4, 2, 9, 4, 7, 2, 3,
       6, 4, 7])

In [53]:
arr.reshape(5,5)

array([[8, 8, 4, 1, 9],
       [1, 4, 6, 6, 5],
       [3, 6, 6, 3, 9],
       [4, 2, 9, 4, 7],
       [2, 3, 6, 4, 7]])

In [54]:
arr.max()

9

In [55]:
arr.argmax()

4

In [58]:
arr.dtype

dtype('int64')

In [64]:
arra= np.arange(0,10)
arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arra[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arra[10:] = 100
arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arra = arr[0:6]
arra

array([0, 1, 2, 3, 4, 5])

In [78]:
arra[:] =100
arra

array([100, 100, 100, 100, 100, 100])

In [79]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [83]:
arra[:] = arr[0:6]
arra

array([100, 100, 100, 100, 100, 100])

In [84]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [91]:
bool_array = arr<9

In [92]:
bool_array 

array([False, False, False, False, False, False,  True,  True,  True,
       False])

In [93]:
arr[arr<9]

array([6, 7, 8])

In [102]:
arr3 = np.arange(25).reshape(5,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [109]:
arr3[1:3,2:4]

array([[ 7,  8],
       [12, 13]])